# Generated by Django 5.0.4 on 2024-04-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_of_submition',
            new_name='date_of_submission',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='taskdescription',
        ),
    ]
