# Generated by Django 5.0.4 on 2024-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_rename_date_of_submition_task_date_of_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200)),
                ('taskdescription', models.CharField(max_length=200)),
                ('date_of_submission', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
