# Generated by Django 5.0.4 on 2024-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='staff',
        ),
    ]
